=== sujatha-persistent/RestDemoNew/sfdc_config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.psltsk.com" xmlns="http://www.psltsk.com"
	elementFormDefault="qualified">

	<!-- configuration is the root element -->
	<xs:element name="configuration">
		<xs:complexType>
			<xs:all>
				<xs:element name="settings" type="settings" />
				<xs:element name="organizations" type="organizationsType" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<!-- settings, child of root configuration -->
	<xs:complexType name="settings">
		<xs:all>
			<xs:element name="thresholds" type="thresholds"></xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="thresholds">
		<xs:all>
			<xs:element name="concurrent-job-threshold" type="xs:int"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="rest-threshold" type="xs:int"
				minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>


	<!-- organizations, child of root configuration -->
	<xs:complexType name="organizationsType">
		<xs:sequence>
			<xs:element name="organization" type="organization"
				minOccurs="1" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="organization">
		<xs:sequence>
			<xs:element name="org-meta-data" type="orgMetaData" />
			<xs:element name="s-objects" type="sObjectsType" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>


	<xs:complexType name="orgMetaData">
		<xs:all>
			<xs:element name="version" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="date-format" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	<xs:complexType name="sObjectsType">
		<xs:sequence>
			<xs:element name="s-object" type="sObject" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sObject">
		<xs:sequence>
			<xs:element name="name" type="objNameEnum" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="objNameEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="User"/>
			<xs:enumeration value="Note"/>
			<xs:enumeration value="Group"/>
			<xs:enumeration value="Account"/>
			<xs:enumeration value="FeedItem"/>
            <xs:enumeration value="FeedComment"/>
            <xs:enumeration value="Attachment"/>
            <xs:enumeration value="GroupMember"/>
            <xs:enumeration value="Document"/>
            <xs:enumeration value="Opportunity"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== sujatha-persistent/RestDemoNew/sfdc_configurations.xml
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns="http://www.psltsk.com"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://wwwpsltsk.com xsd/sfdc_config.xsd">
   <settings>
      <thresholds>
         <concurrent-job-threshold>5</concurrent-job-threshold>
         <rest-threshold>10000</rest-threshold>
      </thresholds>
   </settings>
   <organizations>
      <organization id="1001">
         <org-meta-data>
            <version>v28.0</version>
            <date-format>yyyy-MM-dd'T'HH:mm:ss.SSSZ</date-format>
         </org-meta-data>
         <s-objects>
            <s-object>
               <name>User</name>
            </s-object>
            <s-object>
               <name>Account</name>
            </s-object>
         </s-objects>
      </organization>
   </organizations>
</configuration>
